/**
 * Created by santhosh on 28-09-2020.
 */

public without sharing class FS_Constant {
    public static final String SALES_ORDER_CLOSED = 'Closed';
    public static final String SALES_ORDER_PENDING = 'Pending';
    public static final String SALES_ORDER_POSTED = 'Posted';
    public static final String SALES_ORDER_OPEN = 'Open';
    public static final String SUSTAINING_MEMBER_ITEM_ID = 'SustainingMemberItemId';
}